# Gradle
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Fabric / Minecraft 26.1.2
minecraft_version=26.1.2
loader_version=0.19.2
loom_version=1.16-SNAPSHOT

# Mod Properties
mod_version=1.0.2+26.1.2
maven_group=com.shipovskijkorp.combatextended
archives_base_name=combatextended

# Dependencies
fabric_api_version=0.150.0+26.1.2
